#!/bin/bash

DOIT=/usr/local/bin/foto
echo 25 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio25/direction

until hwclock -s
do
  echo waiting for clock sync
done

while true
do
  START=`date +%s`
  $DOIT
  END=`date +%s`
  DIFF=$((60-$END+$START))

  if (( $DIFF >= 0 )); then
    echo "sleep for $DIFF seconds"
    sleep $DIFF
  fi
done
